version: 0.2
phases:
  install:
    runtime-versions:
      python: latest
      ruby: latest
    commands:
    #Install cfn-lint and cfn-nag
      - pip3 install cfn-lint
      - gem install cfn-nag
  pre_build:
    commands:
      - "aws cloudformation package --template-file application.yaml --s3-bucket hackathon-feb14-artifact-bucket --output-template-file output-application.yaml"
      - "cat application.yaml"
      - "aws cloudformation validate-template --template-body file://application.yaml"
  build:
    commands:
    # Run cfn-lint and cfn-nag test on the cloudformation template
      #- cfn-lint application.yaml
      #- cfn_nag_scan -i application.yaml
      - aws cloudformation package --s3-bucket hackathon-feb14-artifact-bucket --template-file application.yaml --output-template-file output-application.yaml
  post_build:
    commands:
      - echo Build completed on 'date'

artifacts:
  files:
    - application.yaml
    - output-application.yaml


# - CfnNagFailFlag: !FindInMap 
#   - "CfnNagFailFlag"
#   - !Ref CfnNagFailOnWarning
#   - "Flag"
