version: 0.2
phases:
  install:
    runtime-versions:
      python: latest
      ruby: latest
    commands:
    #Install cfn-lint and cfn-nag
      - pip3 install cfn-lint
      - gem install cfn-nag
  pre_build:
    commands:
      - mkdir function-code
      - cp -r src/handlers function-code
      - "aws cloudformation package --template-file application.yaml --s3-bucket hackathon-feb14-artifact-bucket-109882984759 --output-template-file output-application.yaml"
      - "cat application.yaml"
      - "aws cloudformation validate-template --template-body file://application.yaml"
  build:
    commands:
    # Run cfn-lint and cfn-nag test on the cloudformation template
      #- cfn-lint application.yaml
      #- cfn_nag_scan -i application.yaml
    # Zip the Lambda function code and upload it to S3
      # - echo "Zipping deployment package..."
      # - cd function-code
      # - zip -r function-code.zip .
      #- zip -r9 ../deployment-package.zip .
      #- cd ..
      #- zip -g deployment-package.zip 1st-lambda-function.py
      #- zip -g deployment-package.zip 2nd-lambda-function.py
      # - aws s3 cp function-code.zip s3://hackathon-feb14-artifact-bucket-109882984759/
      - aws cloudformation package --s3-bucket hackathon-feb14-artifact-bucket-109882984759 --template-file application.yaml --output-template-file output-application.yaml
  post_build:
    commands:
      - echo Build completed on 'date'

artifacts:
  files:
    - application.yaml
    - output-application.yaml


# - CfnNagFailFlag: !FindInMap 
#   - "CfnNagFailFlag"
#   - !Ref CfnNagFailOnWarning
#   - "Flag"
